server:
  port: 8086

spring:
  application:
    name: loan-service

logging:
  level:
    root: INFO
    com.banking: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
